#!/usr/bin/env python3
"""Generate a Homebrew formula from a verified sdist and uv's runtime lock graph.

No network, Git, package resolver, or Homebrew mutation is performed. Ambiguous
lock resolutions fail closed instead of silently omitting runtime resources.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import tomllib
from urllib.parse import urlparse

VERSION = re.compile(r"(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\Z")
REPOSITORY = re.compile(r"[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9][A-Za-z0-9_.-]*\Z")
SHA256 = re.compile(r"[a-f0-9]{64}\Z")
NAME = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*\Z")


def canonical_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def validated_version(value: str) -> str:
    if not VERSION.fullmatch(value):
        raise ValueError("Only stable numeric X.Y.Z versions can be released to the Homebrew tap")
    return value


def runtime_packages(lock: dict, project: str = "podgrove") -> list[dict]:
    """Return a conservative union of transitive runtime dependencies, in stable order."""
    packages = {}
    for item in lock.get("package", []):
        name = canonical_name(item["name"])
        packages.setdefault(name, []).append(item)
    roots = packages.get(project, [])
    if len(roots) != 1 or roots[0].get("source") != {"editable": "."}:
        raise ValueError("Expected exactly one local project in uv.lock")
    selected = {}

    def visit(package):
        for dependency in package.get("dependencies", []):
            # Include conditional backports on all platforms instead of omitting
            # dependencies needed on an older supported Python. Forked versions
            # and extras need deliberate platform-aware packaging changes.
            if set(dependency) - {"name", "marker"} or "name" not in dependency:
                raise ValueError(f"Ambiguous runtime dependency requires review: {dependency}")
            name = canonical_name(dependency["name"])
            candidates = packages.get(name, [])
            if len(candidates) != 1:
                raise ValueError(f"Missing or ambiguous locked dependency: {name}")
            target = candidates[0]
            if target.get("source") != {"registry": "https://pypi.org/simple"}:
                raise ValueError(f"Runtime dependency must use public PyPI: {name}")
            if name not in selected:
                selected[name] = target
                visit(target)

    visit(roots[0])
    return [selected[name] for name in sorted(selected)]


def source_resource(package: dict) -> tuple[str, str, str]:
    name = canonical_name(package["name"])
    if not NAME.fullmatch(name):
        raise ValueError("Unsafe dependency name")
    source = package.get("sdist", {})
    url = source.get("url", "")
    parsed = urlparse(url)
    if (parsed.scheme != "https" or parsed.netloc != "files.pythonhosted.org"
            or not parsed.path.startswith("/packages/") or parsed.query or parsed.fragment
            or not re.fullmatch(r"[A-Za-z0-9/_.+-]+", parsed.path)):
        raise ValueError(f"Missing or unsafe source URL for {name}")
    digest = source.get("hash", "").removeprefix("sha256:")
    if not SHA256.fullmatch(digest):
        raise ValueError(f"Missing SHA256 for {name}")
    return name, url, digest


def render(*, version: str, sdist_sha256: str, lock: dict, license_id: str,
           repository: str = "podgrove/podgrove") -> str:
    validated_version(version)
    if not REPOSITORY.fullmatch(repository) or not SHA256.fullmatch(sdist_sha256):
        raise ValueError("Invalid repository or sdist checksum")
    if not isinstance(license_id, str) or not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9.+-]*", license_id):
        raise ValueError("Formula requires a single SPDX license identifier")
    project = next(item for item in lock["package"] if item["name"] == "podgrove")
    if project["version"] != version:
        raise ValueError("Locked project version disagrees with release version")
    packages = runtime_packages(lock)
    resources = [source_resource(package) for package in packages]
    lines = [
        "# Generated by scripts/homebrew_formula.py; review source and resource checksums.",
        "class Podgrove < Formula", "  include Language::Python::Virtualenv", "",
        '  desc "Run Compose worktrees on isolated Kubernetes Docker engines"',
        f'  homepage "https://github.com/{repository}"',
        f'  url "https://github.com/{repository}/releases/download/v{version}/podgrove-{version}.tar.gz"',
        f'  sha256 "{sdist_sha256}"', f'  license "{license_id}"', "",
        '  depends_on "python@3.14"',
    ]
    if any(name == "rpds-py" for name, _, _ in resources):
        lines.append('  depends_on "rust" => :build')
    for name, url, digest in resources:
        lines += ["", f'  resource "{name}" do', f'    url "{url}"', f'    sha256 "{digest}"', "  end"]
    lines += ["", "  def install", "    virtualenv_install_with_resources", "  end", "",
              "  def caveats", "    <<~EOS",
              "      Podgrove also needs kubectl and Docker CLI with Compose v2 on PATH.",
              "      A local Docker daemon is not required. Configure an explicit context",
              "      and namespace in podgrove.yml before connecting to Kubernetes.",
              "    EOS", "  end", "", "  test do",
              '    assert_equal version.to_s, shell_output("#{bin}/podgrove --version").strip',
              '    assert_match "--namespace", shell_output("#{bin}/podgrove bootstrap --help")',
              '    (testpath/"podgrove.yml").write <<~YAML', "      version: 1", "      cluster:",
              "        context: homebrew:offline", "        namespace: podgrove-homebrew-test",
              "    YAML", '    system bin/"podgrove", "bootstrap", "--output", testpath/"manifests"',
              '    assert_path_exists testpath/"manifests"', "  end", "end", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sdist", required=True, type=Path)
    parser.add_argument("--project", type=Path, default=Path("pyproject.toml"))
    parser.add_argument("--lock", type=Path, default=Path("uv.lock"))
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    project = tomllib.loads(args.project.read_text())["project"]
    version = validated_version(project["version"])
    if args.sdist.name != f"podgrove-{version}.tar.gz" or not args.sdist.is_file():
        parser.error("sdist filename must match the project version")
    formula = render(version=version, sdist_sha256=hashlib.sha256(args.sdist.read_bytes()).hexdigest(),
                     lock=tomllib.loads(args.lock.read_text()), license_id=project.get("license", ""))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("x") as stream:
        stream.write(formula)
    print(json.dumps({"formula": str(args.output), "version": version}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
